webreader_task:
  description: >
    Visit and read the content of the website at {web_url}.
    Analyze and extract key information that can help answer user questions or support research and reporting tasks.
    Ensure the content is up to date and relevant as of {current_year}.
  expected_output: >
    A structured summary of the main points found on the website, formatted as a clean and organized list of key takeaways.
    Include only the content directly retrieved from the web page.
  agent: web_reader

